// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/VariantA-CommandCentre.tsx": () => import("../components/mockups/VariantA-CommandCentre.tsx"),
  "./components/mockups/VariantB-FocusMode.tsx": () => import("../components/mockups/VariantB-FocusMode.tsx"),
  "./components/mockups/VariantC-DataDense.tsx": () => import("../components/mockups/VariantC-DataDense.tsx"),
  "./components/mockups/WorkflowA-GuidedStepper.tsx": () => import("../components/mockups/WorkflowA-GuidedStepper.tsx"),
  "./components/mockups/WorkflowB-KanbanCommand.tsx": () => import("../components/mockups/WorkflowB-KanbanCommand.tsx")
};
