const express = require('express');
const router = express.Router();
const Anthropic = require('@anthropic-ai/sdk');
const { pool, parseJson } = require('../db');
const { getSystemConfig } = require('../configCache');
const fs = require('fs');
const path = require('path');

function loadPatterns() {
  const dir = path.join(__dirname, '..', 'patterns');
  return fs.readdirSync(dir).filter(f => f.endsWith('.json')).map(f => {
    try { return JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8')); } catch { return null; }
  }).filter(Boolean);
}

function buildProvidersTf(options = {}) {
  const { region = 'canadacentral' } = options;
  return `terraform {
  required_version = ">= 1.5"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 4.0"
    }
    azuread = {
      source  = "hashicorp/azuread"
      version = "~> 2.0"
    }
  }
}

provider "azurerm" {
  features {
    key_vault {
      purge_soft_delete_on_destroy = false
    }
  }
}

provider "azuread" {}
`;
}

function buildTfvarsExample(options = {}) {
  const { environment = 'prod', region = 'canadacentral', namingPrefix = 'mccain' } = options;
  return `environment         = "${environment}"
location            = "${region}"
resource_group_name = "rg-${namingPrefix}-platform-${environment}"
naming_prefix       = "${namingPrefix}"
owner               = "enterprise-architecture@mccain.com"
business_unit       = "Technology"
`;
}

function buildReadme(meta = {}) {
  const { name, referenceId, resourceCount, estimatedMonthlyCost, guardrailsEnforced = [], generatedAt } = meta;
  const guardrailLines = guardrailsEnforced.length
    ? guardrailsEnforced.map(g => `- ${g}`).join('\n')
    : '- Standard McCain security baseline applied';
  return `# ${name || referenceId} — Terraform IaC

Generated by McCain EA Platform on ${generatedAt || new Date().toISOString().split('T')[0]}.

## Resources Deployed
Total resources: **${resourceCount || 'see main.tf'}**

## Estimated Monthly Cost
${estimatedMonthlyCost || 'See Azure Pricing Calculator for estimates'}

## Guardrails Enforced
${guardrailLines}

## Usage
\`\`\`bash
terraform init
terraform plan -var-file=terraform.tfvars.example
terraform apply -var-file=terraform.tfvars.example
\`\`\`

## Requirements
- Terraform >= 1.5
- Azure CLI authenticated (\`az login\`)
- Contributor role on target subscription
`;
}

function buildPatternIaCPrompt(pattern, options = {}) {
  const { environment = 'prod', region = 'canadacentral', namingPrefix = 'mccain' } = options;
  const components = pattern.components || [];
  const guardrails = pattern.guardrails || [];
  const securityConsiderations = pattern.securityConsiderations || [];

  let azureDesignSection = '';
  if (pattern.azureDesign && pattern.azureDesign.data) {
    const allSpecs = [...(pattern.azureDesign.data || []), ...(pattern.azureDesign.compute || [])].slice(0, 8);
    azureDesignSection = '\n## AZURE SKUs (use exactly):\n' +
      allSpecs.map(s => `- ${s.service}: SKU=${s.sku}, ${s.specs}`).join('\n');
  }

  const guardrailsSection = guardrails.length
    ? '\n## GUARDRAILS (enforce as Terraform config):\n' +
      guardrails.map(g => `- [${g.severity}] ${g.area}: ${g.rule}`).join('\n')
    : '';

  const securitySection = securityConsiderations.length
    ? '\n## SECURITY:\n' + securityConsiderations.map(s => `- ${s}`).join('\n')
    : '';

  return `Generate production-grade Terraform HCL for this McCain Foods Enterprise Architecture pattern. Be concise — no inline comments.

## PATTERN
- ID: ${pattern.patternId}
- Name: ${pattern.name}
- Domain: ${pattern.domain}
- Components: ${components.join(', ')}
${azureDesignSection}
${guardrailsSection}
${securitySection}

## RULES
1. azurerm provider ~> 4.0
2. Variables: var.environment, var.location, var.resource_group_name, var.naming_prefix, var.owner, var.business_unit
3. McCain tags on ALL resources: { Environment=var.environment, Owner=var.owner, PatternId="${pattern.patternId}", BusinessUnit=var.business_unit, ManagedBy="Terraform" }
4. locals block for names: "\${var.naming_prefix}-<type>-\${var.environment}"
5. Use data "azurerm_resource_group" (do NOT create RG)
6. azurerm_monitor_diagnostic_setting for applicable resources
7. Managed identity (system-assigned) instead of keys where possible
8. lifecycle { prevent_destroy = true } for stateful resources

Return ONLY valid JSON (no markdown fences, no prose):
{
  "patternId": "${pattern.patternId}",
  "patternName": "${pattern.name}",
  "mainTf": "<complete main.tf HCL>",
  "variablesTf": "<complete variables.tf HCL>",
  "resourceCount": <integer>,
  "estimatedMonthlyCost": "<e.g. $500-800/mo>",
  "guardrailsEnforced": ["<enforced rule>"]
}`;
}

function buildIntakeIaCPrompt(intake, patterns, options = {}) {
  const { environment = 'prod', region = 'canadacentral', namingPrefix = 'mccain' } = options;
  const components = parseJson(intake.components, []);
  const authMethods = parseJson(intake.auth_methods, []);
  const dataTypes = parseJson(intake.data_types, []);
  const relatedPatternIds = parseJson(intake.related_pattern_ids, []);
  const relatedPatterns = patterns.filter(p => relatedPatternIds.includes(p.patternId));
  const newVendors = parseJson(intake.new_vendors, []);

  const patternsSection = relatedPatterns.length
    ? '\n## REFERENCED PATTERNS:\n' +
      relatedPatterns.map(p =>
        `- ${p.patternId}: ${p.name} (${(p.components || []).slice(0, 5).join(', ')})`
      ).join('\n')
    : '';

  return `Generate production-grade Terraform HCL for this McCain Foods architecture request. Be concise — no inline comments.

## REQUEST
- Ref: ${intake.reference_id}
- Title: ${intake.title}
- Type: ${intake.architecture_type || 'N/A'}
- Domain: ${intake.programme_domain || 'N/A'}
- Components: ${components.join(', ') || 'N/A'}
- Hosting: ${intake.hosting_model || 'Azure'}
- Public Facing: ${intake.is_public_facing ? 'Yes' : 'No'}

## SECURITY
- Data Classification: ${intake.data_classification || 'Internal'}
- Data Types: ${dataTypes.join(', ') || 'N/A'}
- Auth: ${authMethods.join(', ') || 'N/A'}
- MFA: ${intake.has_mfa ? 'Yes' : 'No'} | WAF: ${intake.has_waf ? 'Yes' : 'No'} | Zero Trust: ${intake.is_zero_trust_aligned ? 'Yes' : 'No'}
- Encryption at Rest: ${intake.encryption_at_rest ? 'Required' : 'TBD'} | In Transit: ${intake.encryption_in_transit ? 'TLS 1.2+' : 'TBD'}
${patternsSection}

## RULES
1. azurerm ~> 4.0; variables: var.environment, var.location, var.resource_group_name, var.naming_prefix, var.owner, var.business_unit
2. McCain tags: { Environment, Owner, IntakeRef="${intake.reference_id}", BusinessUnit="${intake.business_unit || 'N/A'}", ManagedBy="Terraform" }
3. Confidential/Restricted data → CMK encryption + private endpoints
4. WAF required → azurerm_application_gateway or azurerm_frontdoor_firewall_policy
5. Use data "azurerm_resource_group"; managed identity for service-to-service auth
6. azurerm_monitor_diagnostic_setting for applicable resources
7. lifecycle { prevent_destroy = true } for stateful resources

Return ONLY valid JSON (no markdown fences):
{
  "referenceId": "${intake.reference_id}",
  "title": "${intake.title}",
  "mainTf": "<complete main.tf HCL>",
  "variablesTf": "<complete variables.tf HCL>",
  "resourceCount": <integer>,
  "estimatedMonthlyCost": "<cost estimate>",
  "guardrailsEnforced": ["<enforced rule>"]
}`;
}

function buildSolutionIaCPrompt(solution, patterns, options = {}) {
  const { environment = 'prod', region = 'canadacentral', namingPrefix = 'mccain' } = options;
  const patternIds = parseJson(solution.pattern_ids, []);
  const solutionPatterns = patterns.filter(p => patternIds.includes(p.patternId));
  const deploymentRegions = parseJson(solution.deployment_regions, []);

  const patternsSection = solutionPatterns.map(p =>
    `- ${p.patternId}: ${p.name} — services: ${(p.components || []).slice(0, 6).join(', ')}`
  ).join('\n');

  return `Generate a Terraform root module for this McCain Foods Solution Design composing multiple patterns. Be concise — no inline comments.

## SOLUTION
- Ref: ${solution.reference_id}
- Title: ${solution.title}
- Owner: ${solution.owner || 'N/A'}
- BU: ${solution.business_unit || 'N/A'}
- Regions: ${deploymentRegions.join(', ') || region}

## COMPOSED PATTERNS (${solutionPatterns.length}):
${patternsSection}

## RULES
1. Root main.tf with module blocks: module "<patternId>" { source = "./modules/<patternId>" ... }
2. Each pattern module block must pass: environment, location, resource_group_name, naming_prefix, owner, business_unit
3. Wire outputs between modules where dependencies exist
4. McCain tags: { Environment, Owner, SolutionRef="${solution.reference_id}", ManagedBy="Terraform" }
5. Use data "azurerm_resource_group"; azurerm ~> 4.0

Return ONLY valid JSON (no markdown fences):
{
  "referenceId": "${solution.reference_id}",
  "title": "${solution.title}",
  "mainTf": "<root main.tf with module blocks>",
  "variablesTf": "<root variables.tf>",
  "moduleStubs": {
    ${solutionPatterns.map(p => `"${p.patternId}": "<key resources for ${p.name} — resource type list only>"`).join(',\n    ')}
  },
  "resourceCount": <integer>,
  "estimatedMonthlyCost": "<aggregate cost>",
  "guardrailsEnforced": ["<rule>"]
}`;
}

function assembleFiles(aiResult, options = {}) {
  const files = {
    'providers.tf': buildProvidersTf(options),
    'variables.tf': aiResult.variablesTf || '',
    'main.tf': aiResult.mainTf || '',
    'outputs.tf': `output "resource_group_name" {
  value = data.azurerm_resource_group.main.name
}
`,
    'terraform.tfvars.example': buildTfvarsExample(options),
    'README.md': buildReadme({
      name: aiResult.patternName || aiResult.title,
      referenceId: aiResult.patternId || aiResult.referenceId,
      resourceCount: aiResult.resourceCount,
      estimatedMonthlyCost: aiResult.estimatedMonthlyCost,
      guardrailsEnforced: aiResult.guardrailsEnforced,
      generatedAt: aiResult.generatedAt
    })
  };
  if (aiResult.moduleStubs) {
    for (const [modId, stub] of Object.entries(aiResult.moduleStubs)) {
      files[`modules/${modId}/main.tf`] = `# Module: ${modId}\n# ${stub}\n`;
    }
  }
  return files;
}

function extractJson(text) {
  text = text.trim();
  if (text.startsWith('```')) {
    text = text.replace(/^```(?:json)?\s*\n?/, '').replace(/\n?```\s*$/, '').trim();
  }
  try { return JSON.parse(text); } catch (e) {
    const objMatch = text.match(/\{[\s\S]*\}/);
    const arrMatch = text.match(/\[[\s\S]*\]/);
    const pick = objMatch && arrMatch
      ? (text.indexOf('{') < text.indexOf('[') ? objMatch : arrMatch)
      : (objMatch || arrMatch);
    if (pick) { try { return JSON.parse(pick[0]); } catch {} }
    throw new SyntaxError(`AI response JSON parse failed (response length: ${text.length} chars). Details: ${e.message}`);
  }
}

async function callClaude(prompt) {
  const config = await getSystemConfig().catch(() => ({}));
  const client = new Anthropic();
  const model = config.ai_model_review || 'claude-sonnet-4-5';

  const message = await client.messages.create({
    model,
    max_tokens: 8192,
    messages: [{ role: 'user', content: prompt }]
  });

  return { result: extractJson(message.content[0].text), model };
}

router.post('/pattern/:patternId', async (req, res) => {
  try {
    const patterns = loadPatterns();
    const pattern = patterns.find(p => p.patternId === req.params.patternId);
    if (!pattern) return res.status(404).json({ error: 'Pattern not found' });

    const options = req.body || {};
    const prompt = buildPatternIaCPrompt(pattern, options);
    const { result, model } = await callClaude(prompt);
    result.generatedAt = new Date().toISOString();
    result.model = model;
    result.files = assembleFiles(result, options);

    res.json({ iac: result });
  } catch (err) {
    console.error('IaC pattern generation error:', err);
    res.status(500).json({ error: err.message || 'IaC generation failed' });
  }
});

router.post('/intake/:id', async (req, res) => {
  try {
    const result = await pool.query(
      'SELECT * FROM intake_requests WHERE id::text=$1 OR reference_id=$1',
      [req.params.id]
    );
    if (!result.rows.length) return res.status(404).json({ error: 'Intake not found' });
    const row = result.rows[0];
    const patterns = loadPatterns();
    const options = req.body || {};

    const prompt = buildIntakeIaCPrompt(row, patterns, options);
    const { result: iacResult, model } = await callClaude(prompt);
    iacResult.generatedAt = new Date().toISOString();
    iacResult.model = model;
    iacResult.files = assembleFiles(iacResult, options);

    await pool.query(
      'UPDATE intake_requests SET iac_code=$1, updated_at=NOW() WHERE id=$2',
      [JSON.stringify(iacResult), row.id]
    );

    res.json({ iac: iacResult });
  } catch (err) {
    console.error('IaC intake generation error:', err);
    res.status(500).json({ error: err.message || 'IaC generation failed' });
  }
});

router.get('/intake/:id', async (req, res) => {
  try {
    const result = await pool.query(
      'SELECT iac_code FROM intake_requests WHERE id::text=$1 OR reference_id=$1',
      [req.params.id]
    );
    if (!result.rows.length) return res.status(404).json({ error: 'Intake not found' });
    const iac = parseJson(result.rows[0].iac_code, null);
    res.json({ iac });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

router.post('/solution/:id', async (req, res) => {
  try {
    const result = await pool.query(
      'SELECT * FROM solution_designs WHERE id::text=$1 OR reference_id=$1',
      [req.params.id]
    );
    if (!result.rows.length) return res.status(404).json({ error: 'Solution not found' });
    const row = result.rows[0];
    const patterns = loadPatterns();
    const options = req.body || {};

    const prompt = buildSolutionIaCPrompt(row, patterns, options);
    const { result: iacResult, model } = await callClaude(prompt);
    iacResult.generatedAt = new Date().toISOString();
    iacResult.model = model;
    iacResult.files = assembleFiles(iacResult, options);

    await pool.query(
      'UPDATE solution_designs SET iac_code=$1, updated_at=NOW() WHERE id=$2',
      [JSON.stringify(iacResult), row.id]
    );

    res.json({ iac: iacResult });
  } catch (err) {
    console.error('IaC solution generation error:', err);
    res.status(500).json({ error: err.message || 'IaC generation failed' });
  }
});

router.get('/solution/:id', async (req, res) => {
  try {
    const result = await pool.query(
      'SELECT iac_code FROM solution_designs WHERE id::text=$1 OR reference_id=$1',
      [req.params.id]
    );
    if (!result.rows.length) return res.status(404).json({ error: 'Solution not found' });
    const iac = parseJson(result.rows[0].iac_code, null);
    res.json({ iac });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

module.exports = router;
