// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ea-dashboard-usability/AccessibilityReadability.tsx": () => import("../components/mockups/ea-dashboard-usability/AccessibilityReadability.tsx"),
  "./components/mockups/ea-dashboard-usability/AffordanceVisibility.tsx": () => import("../components/mockups/ea-dashboard-usability/AffordanceVisibility.tsx"),
  "./components/mockups/ea-dashboard-usability/InformationHierarchy.tsx": () => import("../components/mockups/ea-dashboard-usability/InformationHierarchy.tsx")
};
